src/Entity/Contract.php
<?php

namespace App\Entity;

use App\Repository\ContractRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContractRepository::class)]
class Contract
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $startingDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $endDate = null;

    #[ORM\ManyToOne(inversedBy: '_contract')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\ManyToOne(inversedBy: 'contracts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Employee $_employee = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartingDate(): ?\DateTime
    {
        return $this->startingDate;
    }

    public function setStartingDate(\DateTime $startingDate): static
    {
        $this->startingDate = $startingDate;

        return $this;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTime $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->_employee;
    }

    public function setEmployee(?Employee $_employee): static
    {
        $this->_employee = $_employee;

        return $this;
    }
}

src/Form/ContractType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Contract;
use App\Entity\Employee;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContractType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('startingDate', null, [
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('endDate', null, [
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('company', EntityType::class, [
                'class' => Company::class,
                'choice_label' => 'name',
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('_employee', EntityType::class, [
                'class' => Employee::class,
                'choice_label' => 'firstName',
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contract::class,
        ]);
    }
}

src/Form/ContractsType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Contract;
use App\Entity\Employee;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContractsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('startingDate', null, [
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('endDate', null, [
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('company', EntityType::class, [
                'class' => Company::class,
                'choice_label' => 'name',
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
            ->add('_employee', EntityType::class, [
                'class' => Employee::class,
                'choice_label' => 'firstName',
                'required'=>'true',
                'attr'=>['class'=>'form form-control mb-2 mt-1']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contract::class,
        ]);
    }
}

src/Controller/ContractController.php
<?php

namespace App\Controller;

use App\Entity\Contract;
use App\Form\ContractType;
use App\Repository\ContractRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/contract')]
final class ContractController extends AbstractController
{
    #[Route(name: 'app_contract_index', methods: ['GET'])]
    public function index(ContractRepository $contractRepository): Response
    {
        return $this->render('contract/index.html.twig', [
            'contracts' => $contractRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_contract_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contract = new Contract();
        $form = $this->createForm(ContractType::class, $contract);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contract);
            $entityManager->flush();

            return $this->redirectToRoute('app_contract_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contract/new.html.twig', [
            'contract' => $contract,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contract_show', methods: ['GET'])]
    public function show(Contract $contract): Response
    {
        return $this->render('contract/show.html.twig', [
            'contract' => $contract,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_contract_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Contract $contract, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContractType::class, $contract);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contract_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('contract/edit.html.twig', [
            'contract' => $contract,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contract_delete', methods: ['POST'])]
    public function delete(Request $request, Contract $contract, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contract->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($contract);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_contract_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/contract/_delete_form.html.twig
<form method="post" action="{{ path('app_contract_delete', {'id': contract.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contract.id) }}">
    <button class="btn btn-danger">Delete the contract</button>
</form>

templates/contract/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mb-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contract/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contract{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Contract</h1>

    {{ include('contract/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contract_index') }}" class="btn btn-outline-dark mb-2">back to list</a>

    {{ include('contract/_delete_form.html.twig') }}
</div>    
{% endblock %}

templates/contract/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contract index{% endblock %}

{% block body %}
{{ parent() }}
<div class="container">
    <h1 class="text-center mb-3">Contract index</h1>

    <table class="table table-dark">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Starting Date</th>
                <th>End Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contract in contracts %}
            <tr>
                <td>{{ contract.id }}</td>
                <td>{{ contract.employee.lastName }} {{ contract.employee.firstName }}</td>
                <td>{{ contract.startingDate ? contract.startingDate|date('Y-m-d') : '' }}</td>
                <td>{{ contract.endDate ? contract.endDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_contract_show', {'id': contract.id}) }}"class="btn btn-outline-light ">show</a>
                    <a href="{{ path('app_contract_edit', {'id': contract.id}) }}" class="btn btn-outline-success ">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_contract_new') }}" class="btn btn-success ">Create new</a>
</div>    
{% endblock %}

templates/contract/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contract{% endblock %}

{% block body %}
<div class="container">
    <h1>Create a new contract</h1>

    {{ include('contract/_form.html.twig') }}

    <a href="{{ path('app_contract_index') }}" class="btn btn-outline-dark">back to list</a>
</div>    
{% endblock %}

templates/contract/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contract{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center mb-3">Contract : {{ contract.id }}</h1>

    <table class="table table-dark">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contract.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ contract.employee.lastName }} {{ contract.employee.firstName }}</td>
            </tr>
            <tr>
                <th>StartingDate</th>
                <td>{{ contract.startingDate ? contract.startingDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>EndDate</th>
                <td>{{ contract.endDate ? contract.endDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contract_index') }}" class="btn btn-outline-dark mb-2">back to list</a>

    <a href="{{ path('app_contract_edit', {'id': contract.id}) }}" class="btn btn-success mb-2">edit</a>

    {{ include('contract/_delete_form.html.twig') }}
</div>
{% endblock %}